export const MESSAGES = {
  INTERNAL_ERROR: 'Internal server error',
  UNAUTHENTICATED: 'Unauthenticated',
  UNAUTHORIZED: 'Unauthorized',
  NOT_FOUND: 'Not found',
  INVALID_CREDENTIAL: 'Username or password is not correct',
  EMAIL_ALREADY_TAKEN: 'This email is already taken',
  EMAIL_NOT_FOUND: 'This email is not found',
  ACCOUNT_NOT_VERIFY: 'Your account has not yet been verified',
  INVALID_TOKEN: 'This token is not valid',
  INVALID_EMAIL: 'Missing or invalid email',
  INVALID_PASSWORD: 'Missing or invalid password',
  INVALID_NAME: 'Missing or invalid name',
  INVALID_IMAGE: 'Missing or invalid image',
  INVALID_IMAGE_SIZE: 'Missing or invalid image size',
  MUST_BE_GREATER_THAN_OR_EQUAL_TO: '{0} must be greater than or equal to {1}',
  REQUIRED: 'Must not be empty',
  REQUIRED_STRING: 'Must be a string',
  REQUIRED_STRING_IN_RANGE: '{0} must be between {1} and {2} characters',
  REQUIRED_INTEGER: '{0} must be a integer',
  REQUIRED_NUMBER: '{0} must be a number',
  REQUIRED_NUMBER_MIN_VALUE: '{0} must be minimum of {1}',
  REQUIRED_IN_VALUES: '{0} must be one of the following values: {1}',
  REQUIRED_EMAIL_FORMAT: 'Must be a valid email',
  REQUIRED_DATE_FORMAT: 'Must be a valid date string',
  REQUIRED_BOOLEAN: 'Must be a boolean',
  REQUIRED_MAX_LENGTH: 'Length can not exceed {0}',
  CAN_NOT_UPLOAD_FILE: 'Can not upload file',
  REQUIRED_ARRAY: 'Must be a array',
  REQUIRED_OBJECT: 'Must be a object',
};
